const STORE = [
  {
    title: 'Pi LED API',
    category: ['Other'],
    description: 'A turn-key solution for setting up remotely-controlled WS281x LEDs on a Raspberry Pi with Express. Also includes a React front end for ease of use.',
    image: '/images/led.png',
    languages: ['Python', 'Node', 'Express', 'React', 'HTML', 'CSS', 'Javascript', 'AJAX', 'Mocha', 'Chai', 'Jest'],
    repo: 'https://github.com/dannydi12/pi-led-server',
    live: 'https://github.com/dannydi12/pi-led-client#screenshots',
  },
  {
    title: 'Tunezilla',
    category: ['Other'],
    description: 'A simplistic lyric-fetching web app that optionally provides background and historical information about your favorite songs.',
    image: '/images/tunezilla.png',
    languages: ['HTML', 'CSS', 'Javascript', 'jQuery', 'AJAX'],
    repo: 'https://github.com/dannydi12/tunezilla/',
    live: 'https://dannydi12.github.io/tunezilla/',
  },
  {
    title: 'Mocking Text Generator',
    category: ['Other'],
    description: 'A satirical web app to generate randomly capitalized text based on user input. Not to be used for psychological warfare.',
    image: '/images/meme-generator.png',
    languages: ['HTML', 'CSS', 'Javascript', 'jQuery'],
    repo: 'https://github.com/dannydi12/mocking-text-generator',
    live: 'https://dannydi12.github.io/mocking-text-generator/',
  },
  {
    title: 'NPMM',
    category: ['Featured'],
    description: 'An open source project that allows developers to save their favorite packages and install them with NPMM\'s companion CLI.',
    image: '/images/npmm.png',
    languages: ['React', 'Redux', 'Node', 'PostgreSQL', 'Express', 'AJAX', 'Mocha', 'Chai'],
    repo: 'https://github.com/dannydi12/npmm-client',
    live: 'https://npmm.dev',
  },
  {
    title: 'ThoughtBin',
    category: ['Featured'],
    description: 'A frictionless micro-platform that allows users to anonymously share and create content. Eliminates emphasis on followers, likes, or reputation.',
    image: '/images/thoughtbin.png',
    languages: ['React', 'Node', 'PostgreSQL', 'Express', 'WebSockets', 'AJAX', 'Mocha', 'Chai'],
    repo: 'https://github.com/dannydi12/thoughtbin-client',
    live: 'https://thoughtbin.imdan.io',
  },
  {
    title: 'Chocolate Milk Media',
    category: ['Featured'],
    description: 'A freelance project for a film production company. A great case study involving web design and how to be unique on the internet.',
    image: '/images/cmm.png',
    languages: ['HTML', 'CSS', 'Javascript', 'jQuery'],
    repo: 'https://github.com/dannydi12/chocolate-milk-media',
    live: 'https://chocolatemilkmedia.com',
  },
  {
    title: 'My Portfolio',
    category: ['Featured'],
    description: 'Well, this is really meta...',
    image: '/images/portfolio.png',
    languages: ['React', 'HTML', 'CSS', 'Javascript', 'Mocha', 'Chai'],
    repo: 'https://github.com/dannydi12/its-me-daniel',
    live: 'https://imdan.io',
  },
];

export default STORE;
